### ISSUE TITLE
anno_train.txt has nothing!

### ISSUE THREAD

**Issue by Lin427** [Sierkinhane/mtcnn-pytorch#1]

**Comment by Sierkinhane** [comment]
download WIDER FACE (passcode:lsl3) face detection data then store it into ./data_set/face_detection
run > python ./anno_store/tool/format/transform.py change .mat(wider_face_train.mat) into .txt(anno_train.txt)
download CNN_FacePoint face detection and landmark data then store it into ./data_set/face_landmark

or you can cd format/  the anno_train_fixed.txt is the information of face location(please notice that the format we need annotations of face location is x1, y1, x2, y2)
