### ISSUE TITLE
how to generate anno_train_test.txt

### ISSUE THREAD

**Issue by Augnine** [Sierkinhane/mtcnn-pytorch#7]
when run > python mtcnn/data_preprocessing/gen_Rnet_train_data.py

Path does not exist: ./anno_store/anno_train_test.txt

**Comment by flexibility2** [comment]
@zchfaq Could you tell me how to solve this problems? Thanks!

**Comment by Augnine** [comment]
> @zchfaq Could you tell me how to solve this problems? Thanks!

@flexibility2  I think Pnet,Rnet,Onet should use the same annotation file, so I use the "wider_origin_anno.txt" instead
